singleQuote: false
printWidth: 140
tabWidth: 4
useTabs: true
semi: false
trailingComma: "es5"
jsxBracketSameLine: true
jsxSingleQuote: false
quoteProps: "as-needed"
arrowParens: "always"
bracketSpacing: true
htmlWhitespaceSensitivity: css
endOfLine: "lf"
